---
auto        : false
pygments    : false
markdown    : redcarpet2
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]
charset     : UTF-8
exclude     : ["Gemfile", "Gemfile.lock", "Rakefile", "scss"]
title       : "BackChat.io Hookup"
sub_title   : "Reliable messaging over websockets with akka."
rich_title  : "<strong>Hookup</strong> by BackChat.io"
rich_byline : "<strong>Reliable messaging</strong> over websockets"
sponsor:
  byline    : "Maintained by"
  logo      : "imgs/logo.png"
  name      : "BackChat.io"
  url       : "https://backchat.io"
  footer    : "This project is maintained by <a href=\"https://backchat.io\">BackChat.io</a>, the real-time data filtering API for the cloud."

ga_code     : "UA-240612-7"
github:
  username  : "backchatio"
  project   : "hookup"
destination : "../../../target/jekyll"